### ISSUE TITLE
IOS App Crashes with white screen

### ISSUE THREAD

**Issue by vishwasvogga** [ninjasolutions/flutter_opentok#3]
Flutter doctor 
[✓] Flutter (Channel stable, v1.7.8+hotfix.4, on Mac OS X 10.14.6 18G87, locale en-GB)
 
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[✓] Xcode - develop for iOS and macOS (Xcode 10.2.1)
[✓] iOS tools - develop for iOS devices
[✓] Android Studio (version 3.4)
[!] VS Code (version 1.40.1)
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter
[✓] Connected device (2 available)

IOS Log
2019-11-17 20:19:06.621575+0530 Runner[31610:6340769] [DYMTLInitPlatform] platform initialization successful
warning: could not execute support code to read Objective-C class data in the process. This may reduce the quality of type information available.
(lldb) 

![Screenshot 2019-11-17 at 8 21 41 PM](https://user-images.githubusercontent.com/28894009/69009075-f686a980-0977-11ea-99cc-a72b6da7ce9f.png)

**Comment by genert** [comment]
Have seen this happen only once and this was due broken configuration at XCode side and clearing flutter cache/reinstalling helped also. 

If this occurs again, feel free to submit the issue again. 

Will close this for now.
