### ISSUE TITLE
iOS Black Screen Issue

### ISSUE THREAD

**Issue by sava999** [ninjasolutions/flutter_opentok#5]
Hello,

Thanks for creating this library. Are you still maintaining it?

I am having issues running your example on iOS device. On backend when generating session and token I enabled auto archiving, and when I run example code I have sound but no image, it is just black screen. But, after I check archive there everything looks OK, both video and sound are recorded. I am not able to figure this out, I would appreciate any help.

I am testing on iPhone 6s and iOS 13.1.

Thank you

**Comment by genert** [comment]
Yes, we are still maintaining it as we use this library in production iOS app.

The example only displays video & audio when there is already a publisher when creating a session.

Did you try to publish some video & audio from your computer **before** and then run the example?

I reckon the way we built it is the way our app uses it, it is not meant for universal usage but merely displays that using OpenTok is doable for Flutter in iOS.
